apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: nginx:1.17.1@sha256:48cbeee0cb0a3b5e885e36222f969e0a2f41819a68e07aeb6631ca7cb356fed1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: ui-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: ui-config
              mountPath: /etc/nginx/vhost.conf
              subPath: vhost.conf
      volumes:
        - name: ui-config
          configMap:
            name: ui-config
