apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app: api
data:
  LOG_LEVEL: debug
  LOG_SQL_QUERIES: 'true'
  DATABASE_URL: postgres://admin:foobar@postgres/ijci?sslmode=disable # TODO - interpolate vars
  AMQP_EXCHANGE: ijci
  AMQP_ROUTING_KEY: key
  AMQP_URI: amqp://admin:foobar@rabbitmq:5672/ijci # TODO - interpolate vars
