apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  labels:
    app: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: ijbuild/ijci-agent:latest@sha256:38854e950ef01d0481ae73329768e5658163dca7d1a45754697da471e7f9a4a2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: agent-config
        - name: dind
          image: docker:18-dind@sha256:da86d052a9c32ceb60b3f73a28a3acec053f4265e5e0f09924df05bd585fa88e
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          ports:
            - containerPort: 2375
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - docker
                - info
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - docker
                - info
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/docker
              name: dind-storage
              subPathExpr: $(POD_NAME)
      volumes:
        - name: dind-storage
          hostPath:
            path: /tmp/dind
