apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app: api
data:
  LOG_LEVEL: debug
  LOG_SQL_QUERIES: 'true'
  DATABASE_URL: postgres://ijci:hunter2@postgres-postgresql/ijci?sslmode=disable
  AMQP_EXCHANGE: ijci
  AMQP_ROUTING_KEY: key
  AMQP_URI: amqp://ijci:S3FvWruJpe@rabbitmq:5672
